import { useState } from 'react';
import { Link, useOutletContext } from 'react-router-dom';
import { getFeedItemTemplate } from '../utils/getFeedItemTemplate';
import '../css/Form.css';

function Form(props) {

  const [feedItemName, setFeedItemName] = useState('Wikipedia');
  const [feedItemURL, setFeedItemURL] = useState('https://www.wikipedia.org/');

  const [feedItems, setFeedItems] = useOutletContext();

  const handleFeedItemNameChange = (e) => {
    setFeedItemName(e.target.value);
  };

  const handleFeedItemURLChange = (e) => {
    setFeedItemURL(e.target.value);
  };

  const handleFeedItemSubmit = (e) => {
    e.preventDefault();
    const feedItem = getFeedItemTemplate(feedItemName, feedItemURL);
    setFeedItems([...feedItems, feedItem]);
  };

  const handleFeedItemAutoGeneration = () => {
    // create feed items min 6, max 25
    const numItemsToBeAdded = Math.floor(Math.random() * 20) + 6;
    const feedItemsAutoGenerated = [];
    for(let i=1; i<=numItemsToBeAdded; i++) {
      feedItemsAutoGenerated.push(getFeedItemTemplate('Link-' + i, 'https://link-'+i+'.example.com/'));
    }
    setFeedItems([...feedItems, ...feedItemsAutoGenerated]);
  };

  return (
    <>
      <form className='Form' onSubmit={handleFeedItemSubmit}>
        <label>
          <span>Link Name:</span>
          <input type="text" required placeholder="e.g. Wikipedia" value={feedItemName} onChange={handleFeedItemNameChange} />
        </label>
        <label>
          <span>URL:</span>
          <input type="url" required placeholder="https://www.wikipedia.org/" value={feedItemURL} onChange={handleFeedItemURLChange} />
        </label>
        <button type="submit">+ Add</button>
      </form>
      <div className='Form-extras'>
        <span>This button will add random number of autogenerated items to the feed list. (min 6, max 25 items)</span>
        <button onClick={handleFeedItemAutoGeneration}>Poison!</button>
        <Link to="/">Back to List?</Link>
      </div>
    </>
  );

}

export default Form;
