import { useState } from 'react';
import { useOutletContext } from 'react-router-dom';
import { getFeedItemTemplate } from './utils/getFeedItemTemplate';

function Form(props) {

  const [feedItemName, setFeedItemName] = useState('Wikipedia');
  const [feedItemURL, setFeedItemURL] = useState('https://www.wikipedia.org/');

  const [feedItems, setFeedItems] = useOutletContext();

  const handleFeedItemNameChange = (e) => {
    setFeedItemName(e.target.value);
  };

  const handleFeedItemURLChange = (e) => {
    setFeedItemURL(e.target.value);
  };

  const handleFeedItemSubmit = (e) => {
    e.preventDefault();
    const feedItem = getFeedItemTemplate(feedItemName, feedItemURL);
    setFeedItems([...feedItems, feedItem]);
  };

  const handleFeedItemAutoGeneration = () => {
    // create feed items min 6, max 25
    const numItemsToBeAdded = Math.floor(Math.random() * 20) + 6;
    const feedItemsAutoGenerated = [];
    for(let i=1; i<=numItemsToBeAdded; i++) {
      feedItemsAutoGenerated.push(getFeedItemTemplate('Link-' + i, 'https://link-'+i+'.example.com/'));
    }
    setFeedItems([...feedItems, ...feedItemsAutoGenerated]);
  };

  return (
    <>
    <form onSubmit={handleFeedItemSubmit}>
      <input type="text" required placeholder="e.g. Wikipedia" value={feedItemName} onChange={handleFeedItemNameChange} />
      <input type="url" required placeholder="https://www.wikipedia.org/" value={feedItemURL} onChange={handleFeedItemURLChange} />
      <button type="submit">+ add</button>
    </form>
    <div>
      add random items
      <button onClick={handleFeedItemAutoGeneration}>add autogenerated items to the list</button>
    </div>
    </>
  );

}

export default Form;
